const express = require("express");
const { authLimiter } = require("../middleware/rateLimiters");
const { register, login, getMe, verifyEmail, resendVerification, forgotPassword, resetPassword } = require("../controllers/authController");
const protect = require("../middleware/authMiddleware");
const router = express.Router();
router.post("/register", authLimiter, register);
router.post("/login", authLimiter, login);
router.post("/verify-email", authLimiter, verifyEmail);
router.post("/resend-verification", authLimiter, resendVerification);
router.post("/forgot-password", authLimiter, forgotPassword);
router.post("/reset-password", authLimiter, resetPassword);
router.get("/me", protect, getMe);
module.exports = router;
